<?php


define('REMEMBER_ME_COOKIE_NAME_CONSTANT', '6BzWDm3naHL4Xjrr');
define('REMEMBER_ME_COOKIE_VALUE_CONSTANT', '25XxrA4ywcAHXxUN');
define('REMEMBER_ME_COOKIE_EXPIRY', 259200);
define('LOGIN_COOKIE_NAME_CONSTANT', 'bP^%3?2w)HK*L9GM');
define('LOGIN_COOKIE_VALUE_CONSTANT', '*h?<D]+Cn{#Y8E&,');
define('LOGIN_COOKIE_EXPIRY', 259200);

define('USER_ID_SESSION_NAME', 'YELytmfFE7yUpnBd');